name: Tool Mod
description: Xem chi tiết
title: "Xây dựng ROM"
labels: ["Build"]
body:
  - type: markdown
    attributes:
      value: |
        Điền vào thông tin bên dưới để hoàn thành quá trình xây dựng rom
  - type: input
    attributes:
      label: Nhập liên kết
      description: |
        Liên kết Url: http://link_rom/file_zip
        Chỉ hỗ trợ `Android 12` trở lên, nên dùng [link rom của Xiaomi](https://xiaomirom.com/en/series), không hỗ trợ rom port.
      placeholder: "Url:"
      value: "Url: "
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Dùng Recovery mod
      description: |
        Dùng `Twrp`, hoặc `OrangeFox`
        Lưu ý: Nếu chọn Fox một số rom sẽ không có sẵn nó sẽ tự chọn Twrp.
      options:
        - Không thêm
        - OrangeFox
        - TWRP
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Chế độ Mount
      description: Cho phép chỉnh sửa hệ thống hoặc chỉ đọc giống rom gốc.
      options:
        - Theo hệ thống
        - Cho phép ghi đọc
        - Chỉ đọc
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Sau khi hoàn thành toàn bộ hãy ấn vào nút màu xanh lá để hoàn thành `Submit new issue`   
        > Sau khi xây dựng xong bot sẽ gửi link download rom vào bài viết này.
  - type: checkboxes
    attributes:
      label: Tùy chọn
      description: Tích vào ô bên dưới để thêm tính năng khi build rom.
      options:
        - label: "Thêm Tiếng Việt"
        - label: "Thêm GAPP"
        - label: "Thêm âm thanh HARMAN KARDON"
        - label: "Vá hệ thống"
        - label: "Bỏ mã hoá Rom"
          required: false
  - type: dropdown
    attributes:
      label: Chọn ADRENO GPU Driver
      description: Thêm trình điều khiển ADRENO GPU Driver mới vào ROM, nên lựa chọn phù hợp vi xử lý.
      options:
        - Mặc định (không thêm)
        - Phiên bản GPU 725 (SDM8250)
        - Phiên bản GPU 615 (SDM8350)       
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Sever Upload
      description: Chọn sever để tải rom lên, thời gian lưu trữ files tùy sever 10 - 30 ngày.
      options:
        - Gofile
        - Transfer
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Xoá ứng dụng
      description: |
        Tên thư mục ứng dụng ở /system/app/AiAsstVision, priv-app, product v.v
        Thêm dấu # trước tên thư mục là không xóa ứng dụng đó như: #Calculator và được phân biệt bởi khoảng cách.
      render: shell
      value: |
        #Calculator #Calendar #CleanMaster #Health #MIShare #MIShareGlobal #MIUIAod #MIUICalculator #MIUICalculatorGlobal #MIUICalendar #MIUICleanMaster #MIUICleanMasterGlobal-cleaner
        #MIUICompass #MIUICompassGlobal #MIUIMusicGlobal #MIUINotes #MIUIPersonalAssistant #MIUIYellowPage #MIUIYellowPageGlobal #MiGalleryLockScreen #MiGalleryLockScreenGlobal #MiGalleryLockScreenGlobalT
        #MiGalleryLockScreen-T #MiLink #MiLinkGlobal #MiRadio #MiuiAod #MiuiPersonalAssistant #MiuiPlayClient #MiuiWeather #MiuiYellowPage #PersonalAssistant #Weather #Wellbeing #ANGLE #AiAsstVision
        #AiAsstVision_L2 #AiAsstVision_8550 AnalyticsCore AndroidAutoStub #AutoRegistration BaiduIME BasicDreams BookmarkProvider Browser Chrome Chrome64 #CloudPrint2 CtsShimPrebuilt #DMRegService
        #DiracAudioControlService Driver Duo DynamicSystemInstallationService EasterEgg Email FusedLocationProvider #FamilyLinkParentalControls GameCenter GameCenterGlobal Gmail2 GoogleFeedback
        GoogleLocationHistory GoogleNews GoogleOne GoogleOneTimeInitializer #HybridAccessory #HybridPlatform KSICibaEngine MIBrowserGlobal MIBrowserGlobal_removable MIBrowserGlobal_builtin_before_2021
        MICOMMUNITY_OVERSEA MIFinance MIPlayClient MISTORE_OVERSEA MIService MIServiceGlobal MITSMClient #MIUIAICR MIUIAiasstService MIUIBrowser #MIUIBarrage #MIUIBarrageV2 MIUIDriveMode MIUIDuokanReader
        MIUIEmail MIUIGameCenter #MIUIGlobalMinusScreenWidget MIUIHuanji MIUIMiDrive MIUIMiPicks MIUIMusic MIUIMusicT MIUINewHome MIUINewHome_Removable MIUIQuickSearchBox MIUIReporter MIUIScanner
        #MIUISuperMarket #MIUISuperMarket_M2_M3 MIUISystemAppUpdater MIUIVideo MIUIVideoPlayer MIUIVipAccount MIUIVipService MIUIVirtualSim MIUIXiaoAiSpeechEngine MIUIXiaoAiSpeechEngine-matisse
        MIUIYoupin MIUIgreenguard MIpay MINextPay #MiAONService MSA MSA-Global Magisk Maps Meet MarkupGoogle MiBrowser MiBugReport MiCreditInStub MiGameCenterGlobal MiGameCenterSDKService MiGameService
        MiGameService_8550 MiLiveAssistant MiMobileNoti MiMover MiService MiShop MipayService Mirror #MiRadio MiuiAudioMonitor MiuiBugReport MiuiBugReportGlobal MiuiCompass #MiuiContentExtension MiuiDaemon
        MuiScanner MiuiVideoGlobal MiuiVipService Miuigreenguard ModemTestBox Music NewHome NextPay Notes ONS Opera PacProcessor PaymentService PaymentService_Global PersonalSafety PhotoTable Photos
        #PlatformNetworkPermissionConfig #PlayAutoInstallStubApp Podcasts Protips ProxyHandler QuickSearchBox QuickSearchBox_M2M3 RideModeAudio #SecureElement SimAppDialog SmartHome SmartTravel #SogouInput
        SoundPickerGoogle Stk SystemAppUpdater SystemHelper TSMClient #Tag ThirdAppAssistant Traceur TranslationService UPTsmService UserDictionaryProvider Videos VipAccount VirtualSim VoiceAssist
        VoiceAssistAndroidT VoiceTrigger VsimCore WAPPushManager WMService WfdService XMCloudEngine XMPass Xinre XiaoAiSpeechEngine XiaoaiEdgeEngine XiaoaiRecommendation YTMusic YouDaoEngine YouTube
        aiasst_service com.google.mainline.adservices com.iflytek.inputmethod.miui com.miui.qr dpmserviceapp facebook-appmanager facebook-installer facebook-services greenguard mab mi_connect_service
        slaservice talkback tv.danmaku.bili_26 #xdivert

      
